apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: dreamcheck/client
          resources:
            # limits:
            #   cpu: ".5"
            #   memory: "1024Mi"
          env:
            - name: API_URL
              value: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local
            - name: NEXT_PUBLIC_STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: PUBLIC_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
