apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  SECRET_KEY: c2tfdGVzdF81MU5aMFF5SVVsZGZMcDlFMm12dE5nSXdxaXZueTl2MXQ4a092Mk5yVWk4d2Z3VXZwVEFPZGZGN0RPd1JNOXV3QUhYdTJ3NEU1MjFEYndJVFJCcTZ5QVYzWjAwZlFtbllseFc=
  PUBLIC_KEY: cGtfdGVzdF81MU5aMFF5SVVsZGZMcDlFMmRwUDNQblhWUUI0ZTRLTG4yU2lDTXUyYVk4NkRTdmE1dmFHaVFrdTcyUFJpTDBNVzl2N0N3QUFVTDZiZlFKcUcxdHhHWUdQYTAwVTZ6WTQyMVU=