name: test-payment
on:
  workflow_dispatch:
  push:
    paths:
      - "payment/*"
  pull_request:
    paths:
      - "payment/*"

jobs:
  test-payment-service:
    name: Test Payment Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./payment
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: payment/pnpm-lock.yaml

      - name: install deps
        run: pnpm install

      - name: test
        run: pnpm run test
